//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MetalForming.Web.ProduccionService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OrdenVenta", Namespace="http://schemas.datacontract.org/2004/07/MetalForming.BusinessEntities")]
    [System.SerializableAttribute()]
    public partial class OrdenVenta : MetalForming.Web.ProduccionService.BaseEntity {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CantidadField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ClienteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EstadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime FechaEntregaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdProgramaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NumeroField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private MetalForming.Web.ProduccionService.Producto ProductoField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Cantidad {
            get {
                return this.CantidadField;
            }
            set {
                if ((this.CantidadField.Equals(value) != true)) {
                    this.CantidadField = value;
                    this.RaisePropertyChanged("Cantidad");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Cliente {
            get {
                return this.ClienteField;
            }
            set {
                if ((object.ReferenceEquals(this.ClienteField, value) != true)) {
                    this.ClienteField = value;
                    this.RaisePropertyChanged("Cliente");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Estado {
            get {
                return this.EstadoField;
            }
            set {
                if ((object.ReferenceEquals(this.EstadoField, value) != true)) {
                    this.EstadoField = value;
                    this.RaisePropertyChanged("Estado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime FechaEntrega {
            get {
                return this.FechaEntregaField;
            }
            set {
                if ((this.FechaEntregaField.Equals(value) != true)) {
                    this.FechaEntregaField = value;
                    this.RaisePropertyChanged("FechaEntrega");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdPrograma {
            get {
                return this.IdProgramaField;
            }
            set {
                if ((this.IdProgramaField.Equals(value) != true)) {
                    this.IdProgramaField = value;
                    this.RaisePropertyChanged("IdPrograma");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Numero {
            get {
                return this.NumeroField;
            }
            set {
                if ((object.ReferenceEquals(this.NumeroField, value) != true)) {
                    this.NumeroField = value;
                    this.RaisePropertyChanged("Numero");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public MetalForming.Web.ProduccionService.Producto Producto {
            get {
                return this.ProductoField;
            }
            set {
                if ((object.ReferenceEquals(this.ProductoField, value) != true)) {
                    this.ProductoField = value;
                    this.RaisePropertyChanged("Producto");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BaseEntity", Namespace="http://schemas.datacontract.org/2004/07/MetalForming.BusinessEntities.Core")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(MetalForming.Web.ProduccionService.Producto))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(MetalForming.Web.ProduccionService.Material))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(MetalForming.Web.ProduccionService.Maquina))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(MetalForming.Web.ProduccionService.OrdenProduccion))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(MetalForming.Web.ProduccionService.OrdenProduccionMaterial))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(MetalForming.Web.ProduccionService.OrdenProduccionSecuencia))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(MetalForming.Web.ProduccionService.Plan))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(MetalForming.Web.ProduccionService.Programa))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(MetalForming.Web.ProduccionService.OrdenVenta))]
    public partial class BaseEntity : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Producto", Namespace="http://schemas.datacontract.org/2004/07/MetalForming.BusinessEntities")]
    [System.SerializableAttribute()]
    public partial class Producto : MetalForming.Web.ProduccionService.BaseEntity {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescripcionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int StockField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int StockMinimoField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Descripcion {
            get {
                return this.DescripcionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescripcionField, value) != true)) {
                    this.DescripcionField = value;
                    this.RaisePropertyChanged("Descripcion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Stock {
            get {
                return this.StockField;
            }
            set {
                if ((this.StockField.Equals(value) != true)) {
                    this.StockField = value;
                    this.RaisePropertyChanged("Stock");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int StockMinimo {
            get {
                return this.StockMinimoField;
            }
            set {
                if ((this.StockMinimoField.Equals(value) != true)) {
                    this.StockMinimoField = value;
                    this.RaisePropertyChanged("StockMinimo");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Material", Namespace="http://schemas.datacontract.org/2004/07/MetalForming.BusinessEntities")]
    [System.SerializableAttribute()]
    public partial class Material : MetalForming.Web.ProduccionService.BaseEntity {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CantidadField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescripcionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ReservadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int StockField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int StockMinimoField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Cantidad {
            get {
                return this.CantidadField;
            }
            set {
                if ((this.CantidadField.Equals(value) != true)) {
                    this.CantidadField = value;
                    this.RaisePropertyChanged("Cantidad");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Descripcion {
            get {
                return this.DescripcionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescripcionField, value) != true)) {
                    this.DescripcionField = value;
                    this.RaisePropertyChanged("Descripcion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Reservado {
            get {
                return this.ReservadoField;
            }
            set {
                if ((this.ReservadoField.Equals(value) != true)) {
                    this.ReservadoField = value;
                    this.RaisePropertyChanged("Reservado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Stock {
            get {
                return this.StockField;
            }
            set {
                if ((this.StockField.Equals(value) != true)) {
                    this.StockField = value;
                    this.RaisePropertyChanged("Stock");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int StockMinimo {
            get {
                return this.StockMinimoField;
            }
            set {
                if ((this.StockMinimoField.Equals(value) != true)) {
                    this.StockMinimoField = value;
                    this.RaisePropertyChanged("StockMinimo");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Maquina", Namespace="http://schemas.datacontract.org/2004/07/MetalForming.BusinessEntities")]
    [System.SerializableAttribute()]
    public partial class Maquina : MetalForming.Web.ProduccionService.BaseEntity {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CantidadRodillosField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ConfiguracionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescripcionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EstadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MaximoCalienteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MaximoFrioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PLDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PorcentajeFallaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ReduacionFinField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ReduacionInicioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TiempoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TipoField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CantidadRodillos {
            get {
                return this.CantidadRodillosField;
            }
            set {
                if ((object.ReferenceEquals(this.CantidadRodillosField, value) != true)) {
                    this.CantidadRodillosField = value;
                    this.RaisePropertyChanged("CantidadRodillos");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Configuracion {
            get {
                return this.ConfiguracionField;
            }
            set {
                if ((object.ReferenceEquals(this.ConfiguracionField, value) != true)) {
                    this.ConfiguracionField = value;
                    this.RaisePropertyChanged("Configuracion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Descripcion {
            get {
                return this.DescripcionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescripcionField, value) != true)) {
                    this.DescripcionField = value;
                    this.RaisePropertyChanged("Descripcion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Estado {
            get {
                return this.EstadoField;
            }
            set {
                if ((object.ReferenceEquals(this.EstadoField, value) != true)) {
                    this.EstadoField = value;
                    this.RaisePropertyChanged("Estado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MaximoCaliente {
            get {
                return this.MaximoCalienteField;
            }
            set {
                if ((object.ReferenceEquals(this.MaximoCalienteField, value) != true)) {
                    this.MaximoCalienteField = value;
                    this.RaisePropertyChanged("MaximoCaliente");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MaximoFrio {
            get {
                return this.MaximoFrioField;
            }
            set {
                if ((object.ReferenceEquals(this.MaximoFrioField, value) != true)) {
                    this.MaximoFrioField = value;
                    this.RaisePropertyChanged("MaximoFrio");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PLD {
            get {
                return this.PLDField;
            }
            set {
                if ((object.ReferenceEquals(this.PLDField, value) != true)) {
                    this.PLDField = value;
                    this.RaisePropertyChanged("PLD");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PorcentajeFalla {
            get {
                return this.PorcentajeFallaField;
            }
            set {
                if ((object.ReferenceEquals(this.PorcentajeFallaField, value) != true)) {
                    this.PorcentajeFallaField = value;
                    this.RaisePropertyChanged("PorcentajeFalla");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ReduacionFin {
            get {
                return this.ReduacionFinField;
            }
            set {
                if ((object.ReferenceEquals(this.ReduacionFinField, value) != true)) {
                    this.ReduacionFinField = value;
                    this.RaisePropertyChanged("ReduacionFin");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ReduacionInicio {
            get {
                return this.ReduacionInicioField;
            }
            set {
                if ((object.ReferenceEquals(this.ReduacionInicioField, value) != true)) {
                    this.ReduacionInicioField = value;
                    this.RaisePropertyChanged("ReduacionInicio");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Tiempo {
            get {
                return this.TiempoField;
            }
            set {
                if ((object.ReferenceEquals(this.TiempoField, value) != true)) {
                    this.TiempoField = value;
                    this.RaisePropertyChanged("Tiempo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Tipo {
            get {
                return this.TipoField;
            }
            set {
                if ((object.ReferenceEquals(this.TipoField, value) != true)) {
                    this.TipoField = value;
                    this.RaisePropertyChanged("Tipo");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OrdenProduccion", Namespace="http://schemas.datacontract.org/2004/07/MetalForming.BusinessEntities")]
    [System.SerializableAttribute()]
    public partial class OrdenProduccion : MetalForming.Web.ProduccionService.BaseEntity {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CantidadProductoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EstadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<MetalForming.Web.ProduccionService.OrdenProduccionMaterial> MaterialesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NumeroField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private MetalForming.Web.ProduccionService.OrdenVenta OrdenVentaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<MetalForming.Web.ProduccionService.OrdenProduccionSecuencia> SecuenciaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool TomarStockField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CantidadProducto {
            get {
                return this.CantidadProductoField;
            }
            set {
                if ((this.CantidadProductoField.Equals(value) != true)) {
                    this.CantidadProductoField = value;
                    this.RaisePropertyChanged("CantidadProducto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Estado {
            get {
                return this.EstadoField;
            }
            set {
                if ((object.ReferenceEquals(this.EstadoField, value) != true)) {
                    this.EstadoField = value;
                    this.RaisePropertyChanged("Estado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<MetalForming.Web.ProduccionService.OrdenProduccionMaterial> Materiales {
            get {
                return this.MaterialesField;
            }
            set {
                if ((object.ReferenceEquals(this.MaterialesField, value) != true)) {
                    this.MaterialesField = value;
                    this.RaisePropertyChanged("Materiales");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Numero {
            get {
                return this.NumeroField;
            }
            set {
                if ((object.ReferenceEquals(this.NumeroField, value) != true)) {
                    this.NumeroField = value;
                    this.RaisePropertyChanged("Numero");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public MetalForming.Web.ProduccionService.OrdenVenta OrdenVenta {
            get {
                return this.OrdenVentaField;
            }
            set {
                if ((object.ReferenceEquals(this.OrdenVentaField, value) != true)) {
                    this.OrdenVentaField = value;
                    this.RaisePropertyChanged("OrdenVenta");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<MetalForming.Web.ProduccionService.OrdenProduccionSecuencia> Secuencia {
            get {
                return this.SecuenciaField;
            }
            set {
                if ((object.ReferenceEquals(this.SecuenciaField, value) != true)) {
                    this.SecuenciaField = value;
                    this.RaisePropertyChanged("Secuencia");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool TomarStock {
            get {
                return this.TomarStockField;
            }
            set {
                if ((this.TomarStockField.Equals(value) != true)) {
                    this.TomarStockField = value;
                    this.RaisePropertyChanged("TomarStock");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OrdenProduccionMaterial", Namespace="http://schemas.datacontract.org/2004/07/MetalForming.BusinessEntities")]
    [System.SerializableAttribute()]
    public partial class OrdenProduccionMaterial : MetalForming.Web.ProduccionService.BaseEntity {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ComprarField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdOrdenProduccionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private MetalForming.Web.ProduccionService.Material MaterialField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int RequeridoField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Comprar {
            get {
                return this.ComprarField;
            }
            set {
                if ((this.ComprarField.Equals(value) != true)) {
                    this.ComprarField = value;
                    this.RaisePropertyChanged("Comprar");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdOrdenProduccion {
            get {
                return this.IdOrdenProduccionField;
            }
            set {
                if ((this.IdOrdenProduccionField.Equals(value) != true)) {
                    this.IdOrdenProduccionField = value;
                    this.RaisePropertyChanged("IdOrdenProduccion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public MetalForming.Web.ProduccionService.Material Material {
            get {
                return this.MaterialField;
            }
            set {
                if ((object.ReferenceEquals(this.MaterialField, value) != true)) {
                    this.MaterialField = value;
                    this.RaisePropertyChanged("Material");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Requerido {
            get {
                return this.RequeridoField;
            }
            set {
                if ((this.RequeridoField.Equals(value) != true)) {
                    this.RequeridoField = value;
                    this.RaisePropertyChanged("Requerido");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OrdenProduccionSecuencia", Namespace="http://schemas.datacontract.org/2004/07/MetalForming.BusinessEntities")]
    [System.SerializableAttribute()]
    public partial class OrdenProduccionSecuencia : MetalForming.Web.ProduccionService.BaseEntity {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime FechaFinField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime FechaInicioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdOrdenProduccionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private MetalForming.Web.ProduccionService.Maquina MaquinaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int SecuenciaField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime FechaFin {
            get {
                return this.FechaFinField;
            }
            set {
                if ((this.FechaFinField.Equals(value) != true)) {
                    this.FechaFinField = value;
                    this.RaisePropertyChanged("FechaFin");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime FechaInicio {
            get {
                return this.FechaInicioField;
            }
            set {
                if ((this.FechaInicioField.Equals(value) != true)) {
                    this.FechaInicioField = value;
                    this.RaisePropertyChanged("FechaInicio");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdOrdenProduccion {
            get {
                return this.IdOrdenProduccionField;
            }
            set {
                if ((this.IdOrdenProduccionField.Equals(value) != true)) {
                    this.IdOrdenProduccionField = value;
                    this.RaisePropertyChanged("IdOrdenProduccion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public MetalForming.Web.ProduccionService.Maquina Maquina {
            get {
                return this.MaquinaField;
            }
            set {
                if ((object.ReferenceEquals(this.MaquinaField, value) != true)) {
                    this.MaquinaField = value;
                    this.RaisePropertyChanged("Maquina");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Secuencia {
            get {
                return this.SecuenciaField;
            }
            set {
                if ((this.SecuenciaField.Equals(value) != true)) {
                    this.SecuenciaField = value;
                    this.RaisePropertyChanged("Secuencia");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Plan", Namespace="http://schemas.datacontract.org/2004/07/MetalForming.BusinessEntities")]
    [System.SerializableAttribute()]
    public partial class Plan : MetalForming.Web.ProduccionService.BaseEntity {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodigoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EstadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime FechaFinField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime FechaInicioField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Codigo {
            get {
                return this.CodigoField;
            }
            set {
                if ((object.ReferenceEquals(this.CodigoField, value) != true)) {
                    this.CodigoField = value;
                    this.RaisePropertyChanged("Codigo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Estado {
            get {
                return this.EstadoField;
            }
            set {
                if ((object.ReferenceEquals(this.EstadoField, value) != true)) {
                    this.EstadoField = value;
                    this.RaisePropertyChanged("Estado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime FechaFin {
            get {
                return this.FechaFinField;
            }
            set {
                if ((this.FechaFinField.Equals(value) != true)) {
                    this.FechaFinField = value;
                    this.RaisePropertyChanged("FechaFin");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime FechaInicio {
            get {
                return this.FechaInicioField;
            }
            set {
                if ((this.FechaInicioField.Equals(value) != true)) {
                    this.FechaInicioField = value;
                    this.RaisePropertyChanged("FechaInicio");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Programa", Namespace="http://schemas.datacontract.org/2004/07/MetalForming.BusinessEntities")]
    [System.SerializableAttribute()]
    public partial class Programa : MetalForming.Web.ProduccionService.BaseEntity {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CantidadOVField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EstadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime FechaFinField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> FechaFinalizacionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime FechaInicioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdPlanField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MotivoFinalizacionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NumeroField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<MetalForming.Web.ProduccionService.OrdenVenta> OrdenesVentaField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CantidadOV {
            get {
                return this.CantidadOVField;
            }
            set {
                if ((this.CantidadOVField.Equals(value) != true)) {
                    this.CantidadOVField = value;
                    this.RaisePropertyChanged("CantidadOV");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Estado {
            get {
                return this.EstadoField;
            }
            set {
                if ((object.ReferenceEquals(this.EstadoField, value) != true)) {
                    this.EstadoField = value;
                    this.RaisePropertyChanged("Estado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime FechaFin {
            get {
                return this.FechaFinField;
            }
            set {
                if ((this.FechaFinField.Equals(value) != true)) {
                    this.FechaFinField = value;
                    this.RaisePropertyChanged("FechaFin");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> FechaFinalizacion {
            get {
                return this.FechaFinalizacionField;
            }
            set {
                if ((this.FechaFinalizacionField.Equals(value) != true)) {
                    this.FechaFinalizacionField = value;
                    this.RaisePropertyChanged("FechaFinalizacion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime FechaInicio {
            get {
                return this.FechaInicioField;
            }
            set {
                if ((this.FechaInicioField.Equals(value) != true)) {
                    this.FechaInicioField = value;
                    this.RaisePropertyChanged("FechaInicio");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdPlan {
            get {
                return this.IdPlanField;
            }
            set {
                if ((this.IdPlanField.Equals(value) != true)) {
                    this.IdPlanField = value;
                    this.RaisePropertyChanged("IdPlan");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MotivoFinalizacion {
            get {
                return this.MotivoFinalizacionField;
            }
            set {
                if ((object.ReferenceEquals(this.MotivoFinalizacionField, value) != true)) {
                    this.MotivoFinalizacionField = value;
                    this.RaisePropertyChanged("MotivoFinalizacion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Numero {
            get {
                return this.NumeroField;
            }
            set {
                if ((object.ReferenceEquals(this.NumeroField, value) != true)) {
                    this.NumeroField = value;
                    this.RaisePropertyChanged("Numero");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<MetalForming.Web.ProduccionService.OrdenVenta> OrdenesVenta {
            get {
                return this.OrdenesVentaField;
            }
            set {
                if ((object.ReferenceEquals(this.OrdenesVentaField, value) != true)) {
                    this.OrdenesVentaField = value;
                    this.RaisePropertyChanged("OrdenesVenta");
                }
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ProduccionService.IProduccionService")]
    public interface IProduccionService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProduccionService/ListarOrdenesVenta", ReplyAction="http://tempuri.org/IProduccionService/ListarOrdenesVentaResponse")]
        System.Collections.Generic.List<MetalForming.Web.ProduccionService.OrdenVenta> ListarOrdenesVenta();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProduccionService/ListarOrdenesVenta", ReplyAction="http://tempuri.org/IProduccionService/ListarOrdenesVentaResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<MetalForming.Web.ProduccionService.OrdenVenta>> ListarOrdenesVentaAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProduccionService/ListarOrdenesVentaPendiente", ReplyAction="http://tempuri.org/IProduccionService/ListarOrdenesVentaPendienteResponse")]
        System.Collections.Generic.List<MetalForming.Web.ProduccionService.OrdenVenta> ListarOrdenesVentaPendiente();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProduccionService/ListarOrdenesVentaPendiente", ReplyAction="http://tempuri.org/IProduccionService/ListarOrdenesVentaPendienteResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<MetalForming.Web.ProduccionService.OrdenVenta>> ListarOrdenesVentaPendienteAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProduccionService/ListarOrdenesVentaPorPrograma", ReplyAction="http://tempuri.org/IProduccionService/ListarOrdenesVentaPorProgramaResponse")]
        System.Collections.Generic.List<MetalForming.Web.ProduccionService.OrdenVenta> ListarOrdenesVentaPorPrograma(int idPrograma);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProduccionService/ListarOrdenesVentaPorPrograma", ReplyAction="http://tempuri.org/IProduccionService/ListarOrdenesVentaPorProgramaResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<MetalForming.Web.ProduccionService.OrdenVenta>> ListarOrdenesVentaPorProgramaAsync(int idPrograma);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProduccionService/ObtenerOrdenVentaPorNumero", ReplyAction="http://tempuri.org/IProduccionService/ObtenerOrdenVentaPorNumeroResponse")]
        MetalForming.Web.ProduccionService.OrdenVenta ObtenerOrdenVentaPorNumero(string numero);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProduccionService/ObtenerOrdenVentaPorNumero", ReplyAction="http://tempuri.org/IProduccionService/ObtenerOrdenVentaPorNumeroResponse")]
        System.Threading.Tasks.Task<MetalForming.Web.ProduccionService.OrdenVenta> ObtenerOrdenVentaPorNumeroAsync(string numero);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProduccionService/ListarMaterialesPorProducto", ReplyAction="http://tempuri.org/IProduccionService/ListarMaterialesPorProductoResponse")]
        System.Collections.Generic.List<MetalForming.Web.ProduccionService.Material> ListarMaterialesPorProducto(int idProducto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProduccionService/ListarMaterialesPorProducto", ReplyAction="http://tempuri.org/IProduccionService/ListarMaterialesPorProductoResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<MetalForming.Web.ProduccionService.Material>> ListarMaterialesPorProductoAsync(int idProducto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProduccionService/ListarMaquinaPorBusqueda", ReplyAction="http://tempuri.org/IProduccionService/ListarMaquinaPorBusquedaResponse")]
        System.Collections.Generic.List<MetalForming.Web.ProduccionService.Maquina> ListarMaquinaPorBusqueda(string descripcion, string tipo, string pld, string configuracion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProduccionService/ListarMaquinaPorBusqueda", ReplyAction="http://tempuri.org/IProduccionService/ListarMaquinaPorBusquedaResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<MetalForming.Web.ProduccionService.Maquina>> ListarMaquinaPorBusquedaAsync(string descripcion, string tipo, string pld, string configuracion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProduccionService/ObtenerMaquinaPorID", ReplyAction="http://tempuri.org/IProduccionService/ObtenerMaquinaPorIDResponse")]
        MetalForming.Web.ProduccionService.Maquina ObtenerMaquinaPorID(int idMaquina);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProduccionService/ObtenerMaquinaPorID", ReplyAction="http://tempuri.org/IProduccionService/ObtenerMaquinaPorIDResponse")]
        System.Threading.Tasks.Task<MetalForming.Web.ProduccionService.Maquina> ObtenerMaquinaPorIDAsync(int idMaquina);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProduccionService/RegistrarOrdenProduccion", ReplyAction="http://tempuri.org/IProduccionService/RegistrarOrdenProduccionResponse")]
        int RegistrarOrdenProduccion(MetalForming.Web.ProduccionService.OrdenProduccion ordenProduccion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProduccionService/RegistrarOrdenProduccion", ReplyAction="http://tempuri.org/IProduccionService/RegistrarOrdenProduccionResponse")]
        System.Threading.Tasks.Task<int> RegistrarOrdenProduccionAsync(MetalForming.Web.ProduccionService.OrdenProduccion ordenProduccion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProduccionService/ListarOrdenesProduccion", ReplyAction="http://tempuri.org/IProduccionService/ListarOrdenesProduccionResponse")]
        System.Collections.Generic.List<MetalForming.Web.ProduccionService.OrdenProduccion> ListarOrdenesProduccion();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProduccionService/ListarOrdenesProduccion", ReplyAction="http://tempuri.org/IProduccionService/ListarOrdenesProduccionResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<MetalForming.Web.ProduccionService.OrdenProduccion>> ListarOrdenesProduccionAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProduccionService/ObetenerOrdenProduccionPorNumero", ReplyAction="http://tempuri.org/IProduccionService/ObetenerOrdenProduccionPorNumeroResponse")]
        MetalForming.Web.ProduccionService.OrdenProduccion ObetenerOrdenProduccionPorNumero(string numero);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProduccionService/ObetenerOrdenProduccionPorNumero", ReplyAction="http://tempuri.org/IProduccionService/ObetenerOrdenProduccionPorNumeroResponse")]
        System.Threading.Tasks.Task<MetalForming.Web.ProduccionService.OrdenProduccion> ObetenerOrdenProduccionPorNumeroAsync(string numero);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProduccionService/ListarOrdenesProduccionParaEjecucion", ReplyAction="http://tempuri.org/IProduccionService/ListarOrdenesProduccionParaEjecucionRespons" +
            "e")]
        System.Collections.Generic.List<MetalForming.Web.ProduccionService.OrdenProduccion> ListarOrdenesProduccionParaEjecucion();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProduccionService/ListarOrdenesProduccionParaEjecucion", ReplyAction="http://tempuri.org/IProduccionService/ListarOrdenesProduccionParaEjecucionRespons" +
            "e")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<MetalForming.Web.ProduccionService.OrdenProduccion>> ListarOrdenesProduccionParaEjecucionAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProduccionService/ObtenerPlanVigente", ReplyAction="http://tempuri.org/IProduccionService/ObtenerPlanVigenteResponse")]
        MetalForming.Web.ProduccionService.Plan ObtenerPlanVigente();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProduccionService/ObtenerPlanVigente", ReplyAction="http://tempuri.org/IProduccionService/ObtenerPlanVigenteResponse")]
        System.Threading.Tasks.Task<MetalForming.Web.ProduccionService.Plan> ObtenerPlanVigenteAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProduccionService/ListrarProgramasPorPlan", ReplyAction="http://tempuri.org/IProduccionService/ListrarProgramasPorPlanResponse")]
        System.Collections.Generic.List<MetalForming.Web.ProduccionService.Programa> ListrarProgramasPorPlan(int idPlan);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProduccionService/ListrarProgramasPorPlan", ReplyAction="http://tempuri.org/IProduccionService/ListrarProgramasPorPlanResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<MetalForming.Web.ProduccionService.Programa>> ListrarProgramasPorPlanAsync(int idPlan);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProduccionService/GuardarPrograma", ReplyAction="http://tempuri.org/IProduccionService/GuardarProgramaResponse")]
        string GuardarPrograma(MetalForming.Web.ProduccionService.Programa programa);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProduccionService/GuardarPrograma", ReplyAction="http://tempuri.org/IProduccionService/GuardarProgramaResponse")]
        System.Threading.Tasks.Task<string> GuardarProgramaAsync(MetalForming.Web.ProduccionService.Programa programa);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProduccionService/FinalizarPrograma", ReplyAction="http://tempuri.org/IProduccionService/FinalizarProgramaResponse")]
        void FinalizarPrograma(int idPrograma, string motivo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProduccionService/FinalizarPrograma", ReplyAction="http://tempuri.org/IProduccionService/FinalizarProgramaResponse")]
        System.Threading.Tasks.Task FinalizarProgramaAsync(int idPrograma, string motivo);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IProduccionServiceChannel : MetalForming.Web.ProduccionService.IProduccionService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ProduccionServiceClient : System.ServiceModel.ClientBase<MetalForming.Web.ProduccionService.IProduccionService>, MetalForming.Web.ProduccionService.IProduccionService {
        
        public ProduccionServiceClient() {
        }
        
        public ProduccionServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ProduccionServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ProduccionServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ProduccionServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Collections.Generic.List<MetalForming.Web.ProduccionService.OrdenVenta> ListarOrdenesVenta() {
            return base.Channel.ListarOrdenesVenta();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<MetalForming.Web.ProduccionService.OrdenVenta>> ListarOrdenesVentaAsync() {
            return base.Channel.ListarOrdenesVentaAsync();
        }
        
        public System.Collections.Generic.List<MetalForming.Web.ProduccionService.OrdenVenta> ListarOrdenesVentaPendiente() {
            return base.Channel.ListarOrdenesVentaPendiente();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<MetalForming.Web.ProduccionService.OrdenVenta>> ListarOrdenesVentaPendienteAsync() {
            return base.Channel.ListarOrdenesVentaPendienteAsync();
        }
        
        public System.Collections.Generic.List<MetalForming.Web.ProduccionService.OrdenVenta> ListarOrdenesVentaPorPrograma(int idPrograma) {
            return base.Channel.ListarOrdenesVentaPorPrograma(idPrograma);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<MetalForming.Web.ProduccionService.OrdenVenta>> ListarOrdenesVentaPorProgramaAsync(int idPrograma) {
            return base.Channel.ListarOrdenesVentaPorProgramaAsync(idPrograma);
        }
        
        public MetalForming.Web.ProduccionService.OrdenVenta ObtenerOrdenVentaPorNumero(string numero) {
            return base.Channel.ObtenerOrdenVentaPorNumero(numero);
        }
        
        public System.Threading.Tasks.Task<MetalForming.Web.ProduccionService.OrdenVenta> ObtenerOrdenVentaPorNumeroAsync(string numero) {
            return base.Channel.ObtenerOrdenVentaPorNumeroAsync(numero);
        }
        
        public System.Collections.Generic.List<MetalForming.Web.ProduccionService.Material> ListarMaterialesPorProducto(int idProducto) {
            return base.Channel.ListarMaterialesPorProducto(idProducto);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<MetalForming.Web.ProduccionService.Material>> ListarMaterialesPorProductoAsync(int idProducto) {
            return base.Channel.ListarMaterialesPorProductoAsync(idProducto);
        }
        
        public System.Collections.Generic.List<MetalForming.Web.ProduccionService.Maquina> ListarMaquinaPorBusqueda(string descripcion, string tipo, string pld, string configuracion) {
            return base.Channel.ListarMaquinaPorBusqueda(descripcion, tipo, pld, configuracion);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<MetalForming.Web.ProduccionService.Maquina>> ListarMaquinaPorBusquedaAsync(string descripcion, string tipo, string pld, string configuracion) {
            return base.Channel.ListarMaquinaPorBusquedaAsync(descripcion, tipo, pld, configuracion);
        }
        
        public MetalForming.Web.ProduccionService.Maquina ObtenerMaquinaPorID(int idMaquina) {
            return base.Channel.ObtenerMaquinaPorID(idMaquina);
        }
        
        public System.Threading.Tasks.Task<MetalForming.Web.ProduccionService.Maquina> ObtenerMaquinaPorIDAsync(int idMaquina) {
            return base.Channel.ObtenerMaquinaPorIDAsync(idMaquina);
        }
        
        public int RegistrarOrdenProduccion(MetalForming.Web.ProduccionService.OrdenProduccion ordenProduccion) {
            return base.Channel.RegistrarOrdenProduccion(ordenProduccion);
        }
        
        public System.Threading.Tasks.Task<int> RegistrarOrdenProduccionAsync(MetalForming.Web.ProduccionService.OrdenProduccion ordenProduccion) {
            return base.Channel.RegistrarOrdenProduccionAsync(ordenProduccion);
        }
        
        public System.Collections.Generic.List<MetalForming.Web.ProduccionService.OrdenProduccion> ListarOrdenesProduccion() {
            return base.Channel.ListarOrdenesProduccion();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<MetalForming.Web.ProduccionService.OrdenProduccion>> ListarOrdenesProduccionAsync() {
            return base.Channel.ListarOrdenesProduccionAsync();
        }
        
        public MetalForming.Web.ProduccionService.OrdenProduccion ObetenerOrdenProduccionPorNumero(string numero) {
            return base.Channel.ObetenerOrdenProduccionPorNumero(numero);
        }
        
        public System.Threading.Tasks.Task<MetalForming.Web.ProduccionService.OrdenProduccion> ObetenerOrdenProduccionPorNumeroAsync(string numero) {
            return base.Channel.ObetenerOrdenProduccionPorNumeroAsync(numero);
        }
        
        public System.Collections.Generic.List<MetalForming.Web.ProduccionService.OrdenProduccion> ListarOrdenesProduccionParaEjecucion() {
            return base.Channel.ListarOrdenesProduccionParaEjecucion();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<MetalForming.Web.ProduccionService.OrdenProduccion>> ListarOrdenesProduccionParaEjecucionAsync() {
            return base.Channel.ListarOrdenesProduccionParaEjecucionAsync();
        }
        
        public MetalForming.Web.ProduccionService.Plan ObtenerPlanVigente() {
            return base.Channel.ObtenerPlanVigente();
        }
        
        public System.Threading.Tasks.Task<MetalForming.Web.ProduccionService.Plan> ObtenerPlanVigenteAsync() {
            return base.Channel.ObtenerPlanVigenteAsync();
        }
        
        public System.Collections.Generic.List<MetalForming.Web.ProduccionService.Programa> ListrarProgramasPorPlan(int idPlan) {
            return base.Channel.ListrarProgramasPorPlan(idPlan);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<MetalForming.Web.ProduccionService.Programa>> ListrarProgramasPorPlanAsync(int idPlan) {
            return base.Channel.ListrarProgramasPorPlanAsync(idPlan);
        }
        
        public string GuardarPrograma(MetalForming.Web.ProduccionService.Programa programa) {
            return base.Channel.GuardarPrograma(programa);
        }
        
        public System.Threading.Tasks.Task<string> GuardarProgramaAsync(MetalForming.Web.ProduccionService.Programa programa) {
            return base.Channel.GuardarProgramaAsync(programa);
        }
        
        public void FinalizarPrograma(int idPrograma, string motivo) {
            base.Channel.FinalizarPrograma(idPrograma, motivo);
        }
        
        public System.Threading.Tasks.Task FinalizarProgramaAsync(int idPrograma, string motivo) {
            return base.Channel.FinalizarProgramaAsync(idPrograma, motivo);
        }
    }
}
