//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.34209
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MetalForming.Web.MantenimientoService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Material", Namespace="http://schemas.datacontract.org/2004/07/MetalForming.BusinessEntities")]
    [System.SerializableAttribute()]
    public partial class Material : MetalForming.Web.MantenimientoService.BaseEntity {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int AnchoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CantidadField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodigoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescripcionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int EspesorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int EstadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string InformacionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int LargoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PresionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ReservadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int StockField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int StockMinimoField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Ancho {
            get {
                return this.AnchoField;
            }
            set {
                if ((this.AnchoField.Equals(value) != true)) {
                    this.AnchoField = value;
                    this.RaisePropertyChanged("Ancho");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Cantidad {
            get {
                return this.CantidadField;
            }
            set {
                if ((this.CantidadField.Equals(value) != true)) {
                    this.CantidadField = value;
                    this.RaisePropertyChanged("Cantidad");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Codigo {
            get {
                return this.CodigoField;
            }
            set {
                if ((object.ReferenceEquals(this.CodigoField, value) != true)) {
                    this.CodigoField = value;
                    this.RaisePropertyChanged("Codigo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Descripcion {
            get {
                return this.DescripcionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescripcionField, value) != true)) {
                    this.DescripcionField = value;
                    this.RaisePropertyChanged("Descripcion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Espesor {
            get {
                return this.EspesorField;
            }
            set {
                if ((this.EspesorField.Equals(value) != true)) {
                    this.EspesorField = value;
                    this.RaisePropertyChanged("Espesor");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Estado {
            get {
                return this.EstadoField;
            }
            set {
                if ((this.EstadoField.Equals(value) != true)) {
                    this.EstadoField = value;
                    this.RaisePropertyChanged("Estado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Informacion {
            get {
                return this.InformacionField;
            }
            set {
                if ((object.ReferenceEquals(this.InformacionField, value) != true)) {
                    this.InformacionField = value;
                    this.RaisePropertyChanged("Informacion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Largo {
            get {
                return this.LargoField;
            }
            set {
                if ((this.LargoField.Equals(value) != true)) {
                    this.LargoField = value;
                    this.RaisePropertyChanged("Largo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Presion {
            get {
                return this.PresionField;
            }
            set {
                if ((this.PresionField.Equals(value) != true)) {
                    this.PresionField = value;
                    this.RaisePropertyChanged("Presion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Reservado {
            get {
                return this.ReservadoField;
            }
            set {
                if ((this.ReservadoField.Equals(value) != true)) {
                    this.ReservadoField = value;
                    this.RaisePropertyChanged("Reservado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Stock {
            get {
                return this.StockField;
            }
            set {
                if ((this.StockField.Equals(value) != true)) {
                    this.StockField = value;
                    this.RaisePropertyChanged("Stock");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int StockMinimo {
            get {
                return this.StockMinimoField;
            }
            set {
                if ((this.StockMinimoField.Equals(value) != true)) {
                    this.StockMinimoField = value;
                    this.RaisePropertyChanged("StockMinimo");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BaseEntity", Namespace="http://schemas.datacontract.org/2004/07/MetalForming.BusinessEntities.Core")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(MetalForming.Web.MantenimientoService.Material))]
    public partial class BaseEntity : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="MantenimientoService.IMantenimientoService")]
    public interface IMantenimientoService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMantenimientoService/ListarMateriales", ReplyAction="http://tempuri.org/IMantenimientoService/ListarMaterialesResponse")]
        System.Collections.Generic.List<MetalForming.Web.MantenimientoService.Material> ListarMateriales(string codigo, string descripcion, int tipo, int min, int max, int estado);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMantenimientoService/ListarMateriales", ReplyAction="http://tempuri.org/IMantenimientoService/ListarMaterialesResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<MetalForming.Web.MantenimientoService.Material>> ListarMaterialesAsync(string codigo, string descripcion, int tipo, int min, int max, int estado);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMantenimientoService/GuardarMaterial", ReplyAction="http://tempuri.org/IMantenimientoService/GuardarMaterialResponse")]
        string GuardarMaterial(MetalForming.Web.MantenimientoService.Material material);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMantenimientoService/GuardarMaterial", ReplyAction="http://tempuri.org/IMantenimientoService/GuardarMaterialResponse")]
        System.Threading.Tasks.Task<string> GuardarMaterialAsync(MetalForming.Web.MantenimientoService.Material material);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMantenimientoService/ActualizarMaterial", ReplyAction="http://tempuri.org/IMantenimientoService/ActualizarMaterialResponse")]
        string ActualizarMaterial(MetalForming.Web.MantenimientoService.Material material);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMantenimientoService/ActualizarMaterial", ReplyAction="http://tempuri.org/IMantenimientoService/ActualizarMaterialResponse")]
        System.Threading.Tasks.Task<string> ActualizarMaterialAsync(MetalForming.Web.MantenimientoService.Material material);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMantenimientoService/EliminarMaterial", ReplyAction="http://tempuri.org/IMantenimientoService/EliminarMaterialResponse")]
        string EliminarMaterial(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMantenimientoService/EliminarMaterial", ReplyAction="http://tempuri.org/IMantenimientoService/EliminarMaterialResponse")]
        System.Threading.Tasks.Task<string> EliminarMaterialAsync(int id);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IMantenimientoServiceChannel : MetalForming.Web.MantenimientoService.IMantenimientoService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MantenimientoServiceClient : System.ServiceModel.ClientBase<MetalForming.Web.MantenimientoService.IMantenimientoService>, MetalForming.Web.MantenimientoService.IMantenimientoService {
        
        public MantenimientoServiceClient() {
        }
        
        public MantenimientoServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MantenimientoServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MantenimientoServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MantenimientoServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Collections.Generic.List<MetalForming.Web.MantenimientoService.Material> ListarMateriales(string codigo, string descripcion, int tipo, int min, int max, int estado) {
            return base.Channel.ListarMateriales(codigo, descripcion, tipo, min, max, estado);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<MetalForming.Web.MantenimientoService.Material>> ListarMaterialesAsync(string codigo, string descripcion, int tipo, int min, int max, int estado) {
            return base.Channel.ListarMaterialesAsync(codigo, descripcion, tipo, min, max, estado);
        }
        
        public string GuardarMaterial(MetalForming.Web.MantenimientoService.Material material) {
            return base.Channel.GuardarMaterial(material);
        }
        
        public System.Threading.Tasks.Task<string> GuardarMaterialAsync(MetalForming.Web.MantenimientoService.Material material) {
            return base.Channel.GuardarMaterialAsync(material);
        }
        
        public string ActualizarMaterial(MetalForming.Web.MantenimientoService.Material material) {
            return base.Channel.ActualizarMaterial(material);
        }
        
        public System.Threading.Tasks.Task<string> ActualizarMaterialAsync(MetalForming.Web.MantenimientoService.Material material) {
            return base.Channel.ActualizarMaterialAsync(material);
        }
        
        public string EliminarMaterial(int id) {
            return base.Channel.EliminarMaterial(id);
        }
        
        public System.Threading.Tasks.Task<string> EliminarMaterialAsync(int id) {
            return base.Channel.EliminarMaterialAsync(id);
        }
    }
}
